import numpy as np
from math import gcd


def conv(f,g,mode = 'circ'):
    if mode == 'circ':
        return np.fft.ifft(np.fft.fft(f)*np.fft.fft(g))
    if mode == 'linear':
        return np.convolve(f,g)
    return 0

def mult_group(M):
    units = []
    for a in range(1, M):
        if gcd(a, M) == 1:
            units.append(a)
    return units

def dyadic_scaling(M):
    scales = []
    for j in range(0, int(np.log2(M))):
        scales.append(2**j)
    return scales

class scattering_net:
    """
    This class implements general scattering networks on finite cyclic groups.
    """

    def __init__(self, dim, layers, mode='circ', struct = 'vec'):
        """
        dim (int): input dimension
        layers (list): list of building blocks for each layer consisting of frame, nonlinearity, and pooling operator
        struct (string): determines structure of scattering transform (tree or stacked vector)
        """
        self.dim = dim
        self.layers = layers
        self.mode = mode
        self.struct = struct


    def compute_ST(self, f_in):
        """
        Computes the scattering transform
        f (np.array): input signal
        output (list or np.array): scattering transform of input signal as tree structure or stacked vector 
        """
        nodes = [[f_in]]
        output_tree = [[conv(f_in,self.layers[0][0][0],self.mode)]]
        output_vec = output_tree[0].copy()
        for l in range(1,len(self.layers)):
            layer = self.layers[l]
            new_nodes = []
            new_outputs = [] 
            for f in nodes[l-1]:
                for k in range(1,len(layer[0])):
                    node = layer[2](layer[1](conv(f,layer[0][k],self.mode)))
                    out = conv(node,layer[0][0],self.mode) 
                    new_nodes.append(node)
                    new_outputs.append(out)
                    output_vec.append(out)
            nodes.append(new_nodes)
            output_tree.append(new_outputs)
        if self.struct == 'tree':
            return output_tree
        return np.hstack(output_vec)

    """
    Frames
    """
    @staticmethod
    def WH_frame(vec,R):
        """
        Weyl--Heisenberg frame for C^M
        vec (np.array): prototype function
        output (list): frame elements generated by prototype function vec
        """
        frame = []
        M = np.size(vec)
        frame.append(vec)
        for k in range(1,int(M/R)):
            g = np.fft.ifft(np.roll(np.fft.fft(vec),k*R))
            frame.append(g)
        return frame
    
    def wavelet_frame(phi,psi):
        """
        Wavelet frame for C^M
        phi (np.array): father wavelet 
        psi (np.array): mother wavelet
        output (list): frame elements, i.e., phi and dilated versions of psi
        """
        frame = []
        frame.append(phi)
        M = np.size(psi)
        for l in dyadic_scaling(M):
            frame.append(scattering_net.subsampling(psi,l))
        return frame
    
    """
    Some nonlinearities
    """
    @staticmethod
    def modulus(z):
        return np.abs(z)
    @staticmethod
    def modulus2(z):
        return np.abs(z)**2
    @staticmethod
    def relu(z):
        return np.maximum(0,z.real)+1j*np.maximum(0,z.imag)
    @staticmethod
    def arctan(z):
        return np.arctan(z)
    @staticmethod
    def sigmoid(z):
        return 1/(1+np.exp(-z.real))-1/2+1j*(1/(1+np.exp(-z.imag))-1/2)
    
    """
    Pooling operators
    """
    @staticmethod
    def identity(signal):
        return signal
    @staticmethod
    def subsampling(signal, S):
        d = np.size(signal) 
        res = np.zeros(np.size(signal), dtype=complex)
        for k in range(d):
            res[k] = signal[k*S % d]
        return res